apiVersion: skaffold/v1beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: eu.gcr.io/kupping-lite/website
deploy:
  helm:
    releases:
    - name: website-helm
      chartPath: ./charts
      wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image: eu.gcr.io/kupping-lite/website
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
        #some.key: someValue