apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/k3s-tests/website
    context: .
deploy:
  kubectl:
    manifests:
    # - charts/kubectl/configmap.yaml
    - charts/kubectl/development.yaml
    - charts/kubectl/service.yaml
    # - charts/kubectl/gateway.yaml
    - charts/kubectl/virtualservice.yaml
