apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: eu.gcr.io/k3s-tests/website
    context: .
deploy:
  kubectl:
    manifests:
    # - charts/configmap.yaml
    - charts/development.yaml
    - charts/service.yaml
    - charts/gateway.yaml
    - charts/virtualservice.yaml
