version: '2'
services:
    mongo:
        image: mongo:4.0.1
        environment:
            - MONGO_INITDB_ROOT_USERNAME=kuppinguserusuario
            - MONGO_INITDB_ROOT_PASSWORD=123asd123z
            - MONGO_INITDB_DATABASE=kupping
        volumes:
            - "./data:/data"
        ports:
            - 27017:27017
    backend:
        build: .
        restart: always
        environment:
            docker: "true"
            PORT: 80
            MONGO: "mongo"
            MONGO_PORT: ":27017"
            MONGO_PREFIX: "mongodb://"
            MONGO_USER: "kuppinguserusuario"
            MONGO_PASSWORD: "123asd123z"
            JWT_SECRET: "ma££sanABwinfquw123@@££££€"
        ports:
            - "9443:8083"
        volumes:
            - ".:/rpg-backend"
        depends_on: 
            - mongo
