apiVersion: v1
kind: Service
metadata:
  labels:
    app: website
  name: website-service
  namespace: default
spec:
  ports:
  - port: 80
    name: http-nginx
    protocol: TCP
    targetPort: 80
  - port: 443
    name: https-nginx
    protocol: TCP
    targetPort: 443
  selector:
    app: website
  type: ClusterIP